package loader_test

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/autobrr/harbrr/internal/indexer/cardigann/loader"
)

// TestIsSecretCases pins the classifier's behaviour on the corpus shapes that
// matter most — the ones a name-only or type-only rule would get wrong.
func TestIsSecretCases(t *testing.T) {
	t.Parallel()

	cases := []struct {
		typ, name string
		want      bool
	}{
		{"password", "password", true},  // the obvious case
		{"text", "cookie", true},        // text-typed secret (126 defs)
		{"text", "apikey", true},        // text-typed secret (105 defs)
		{"text", "passkey", true},       // text-typed secret
		{"text", "pin", true},           // login PIN posted in the form (7 defs)
		{"text", "2facode", true},       // tracker 2FA code (25 defs)
		{"text", "alt2fatoken", true},   // alternate 2FA token
		{"text", "staffpass", true},     // staff password
		{"text", "rsskey", true},        // rss key
		{"text", "username", false},     // identifier, not a secret (plaintext)
		{"text", "useragent", false},    // UA string, not a secret
		{"text", "apiurl", false},       // a URL, not a key
		{"checkbox", "usetoken", false}, // boolean toggle, not a secret
		{"checkbox", "use_fl_tokens", false},
		{"info_cookie", "info_cookie", false}, // display-only help text
		{"info_key", "info_key", false},
		{"info_2fa", "info_2fa", false},
		{"select", "sort", false},
		{"select", "freeleech", false},
	}
	for _, c := range cases {
		t.Run(c.typ+"/"+c.name, func(t *testing.T) {
			t.Parallel()
			got := loader.SettingsField{Type: c.typ, Name: c.name}.IsSecret()
			if got != c.want {
				t.Errorf("IsSecret(type=%q name=%q) = %v, want %v", c.typ, c.name, got, c.want)
			}
		})
	}
}

// TestSecretClassifierCorpusAudit classifies every distinct (type, name) setting
// across the vendored corpus and pins the result to a golden file. A re-vendor
// that introduces a new secret-shaped field changes the golden, forcing a human
// to confirm the classifier still encrypts/redacts it. Regenerate with
// UPDATE_GOLDEN=1 go test -race -count=1 ./internal/indexer/cardigann/loader/.
func TestSecretClassifierCorpusAudit(t *testing.T) {
	t.Parallel()

	defs, skipped, err := loader.New("").LoadAll()
	if err != nil {
		t.Fatalf("LoadAll: %v", err)
	}
	if len(defs) == 0 {
		t.Fatal("no definitions loaded")
	}
	t.Logf("audited %d definitions (%d skipped)", len(defs), len(skipped))

	seen := map[string]bool{}
	for _, def := range defs {
		for _, s := range def.Settings {
			line := fmt.Sprintf("type=%-18s name=%-24s secret=%v", s.Type, s.Name, s.IsSecret())
			seen[line] = true
		}
	}
	lines := make([]string, 0, len(seen))
	for l := range seen {
		lines = append(lines, l)
	}
	sort.Strings(lines)

	var buf []byte
	buf = append(buf, "# Secret-field classification audit over the vendored corpus.\n"...)
	buf = append(buf, "# Generated by TestSecretClassifierCorpusAudit (UPDATE_GOLDEN=1 to refresh).\n"...)
	buf = append(buf, "# A change here means a setting's secret/plaintext classification moved —\n"...)
	buf = append(buf, "# confirm any new secret-shaped field is classified secret=true.\n"...)
	for _, l := range lines {
		buf = append(buf, l...)
		buf = append(buf, '\n')
	}

	golden := filepath.Join("testdata", "secret_audit.txt")
	if os.Getenv("UPDATE_GOLDEN") != "" {
		if err := os.WriteFile(golden, buf, 0o600); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("wrote %s (%d distinct settings)", golden, len(lines))
		return
	}

	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden (run UPDATE_GOLDEN=1 go test -race -count=1 ./internal/indexer/cardigann/loader/ to create): %v", err)
	}
	if string(want) != string(buf) {
		t.Errorf("secret_audit.txt is stale — re-run with UPDATE_GOLDEN=1 and review the diff")
	}
}
